### ISSUE TITLE
Can't see highlighted item

### ISSUE THREAD

**Issue by RonItelman** [kamranahmedse/driver.js#31]
Image attached. No error messages in the console. 

code:
```
const driver = new Driver({
    opacity:1
  });
  driver.highlight({
    element: '.subNavOptionW[data-option="Topics"]',
    popover: {
      title: 'Title for the Popover',
      description: 'Description for it',
    }
  });
```

<img width="1269" alt="screen shot 2018-03-17 at 6 40 32 pm" src="https://user-images.githubusercontent.com/5273970/37561372-c74642de-2a12-11e8-826b-67757feac6c2.png">

**Comment by kamranahmedse** [comment]
Seems to be similar to https://github.com/kamranahmedse/driver.js/issues/9#issuecomment-373104623

Is the text color white? Could you please try setting the `stageBackground` to some dark color and test e.g.

```javascript
const driver = new Driver({
    stageBackground: 'blue'
});
```

**Comment by raisoblast** [comment]
I have same issue when parent div have `position: relative` and `z-index` style.

![screenshot from 2018-03-19 16-24-24](https://user-images.githubusercontent.com/753819/37587911-38e6d8be-2b93-11e8-8ef8-6addfef3c903.png)

template:
```
<div style="position: relative; z-index: 1;">
	<div id="hello">
		<input type="text">
		<button id="btnHello">Hello</button>
	</div>
</div>
```

**Comment by kamranahmedse** [comment]
Ah, looks like stacking contexts issue, will look into it. Thanks @raisoblast

**Comment by huzeyfecoskun** [comment]
![screenshot_1](https://user-images.githubusercontent.com/673053/37643202-dded4dbe-2c30-11e8-9244-902ea7e31c68.png)
did you solve this issue ?  i also cant click to the overlay to close highlight

**Comment by sarmadbokhari** [comment]
I have a similar issue in Chrome, Firefox, and Safari whereby hovering over the selected element causes it to flicker and go white/blank. Tried looking for another issue that might address this but couldn't find one. Tried toggling a bunch of options and I'm still experiencing it. @kamranahmedse any ideas if it's related to this issue?

**Comment by raisoblast** [comment]
@kamranahmedse, currently I solve the issue by going back using canvas method

**Comment by kamranahmedse** [comment]
@raisoblast which I won't recommend because it has terrible and flickery performance in firefox and might not work at all in IE (works smoothly in chrome though). I am almost done with the fix, will push it tonight.

@sarmadbokhari let's test after this fix and see if it solves for you.

**Comment by kamranahmedse** [comment]
Fixed in the latest release. Could all of you guys please test? :)

**Comment by raisoblast** [comment]
![screenshot from 2018-03-22 10-35-26](https://user-images.githubusercontent.com/753819/37749968-15fa3932-2dbd-11e8-9030-27642139f7fa.png)
awesome, it works now, thanks @kamranahmedse

**Comment by sarmadbokhari** [comment]
@kamranahmedse I'm still getting the same issue after upgrading to 0.3.6 unfortunately. Here's a screen cast of what I'm seeing: https://spaces.hightail.com/space/iDRl2s1est/files/fi-fb14b0e8-cbb1-4891-b9a8-dd5271702b01/fv-3c514bf8-124f-4384-9245-11f50865de34/driver.js%20hover.mov

**Comment by kamranahmedse** [comment]
Aha looks like this checkbox plugin that you are using is somehow affecting it. Since the current issue has been resolved, could you possibly create a reproducing plunker with this part of your app and open a new issue?

**Comment by CatMLily** [comment]
l 'm still getting the same issue in version 0.3.8
![image](https://user-images.githubusercontent.com/19372540/38234104-673f4648-374f-11e8-995c-54c76492bdde.png)

**Comment by kamranahmedse** [comment]
@CatMLily could you possibly create a plunkr for that?

**Comment by CatMLily** [comment]
@kamranahmedse  l use it in my React project.
Code
`import Driver from 'driver.js';
import 'driver.js/dist/driver.min.css';
class xxx extends Component {
componentDidMount() {
    const driver = new Driver({stageBackground: 'blue'});
    document.getElementById('test')
    .addEventListener('focus', (e) => {
      driver.highlight({
        element: '#test',
      });
    });
  }
// ....more code
render() {
  <div className={['AddWrapper', this.state.addShow ? 'addFadeIn':'addFadeOut'].join(' ')}>
     <input placeholder='TODO' id='test'/>
     <button>ADD</button>
  </div>
}
}
`
If can‘t find problems from these codes, l'll  provide my git repository.
Thanks !！

**Comment by kamranahmedse** [comment]
It would be difficult to identify the issue from this as it is probably happening because of some CSS conflict.

**Comment by 00cpxxx** [comment]
Was this fixed? I'm still seeing the issue in today's git dist. Should I open a new bug report?

**Comment by kamranahmedse** [comment]
@00cpxxx yes it was fixed but note that in some edge cases when you can't get around the z-index stacking context issues, you will have to use the non-animated version. 

But anyways, give the non-animated version a try and feel free to open an issue with a reproducing plunker

**Comment by 00cpxxx** [comment]
@kamranahmedse thanks for the quick reply, non-animated works as expected.

**Comment by kamranahmedse** [comment]
Then it is probably the z-index issue. If you are fine with using the non-animated version then well in good. Otherwise, if you can provide the plunker, I can look at it and see what might be causing the issue. You might have to rearrange some elements or CSS to make it work.

**Comment by mostafabita** [comment]
@kamranahmedse your fix (.driver-fix-stacking class) doesn't work fine! for example I'm using driver.js in Angular Material Sidenav and I looks:
![image](https://user-images.githubusercontent.com/10722240/112469574-42750a00-8d87-11eb-8f4d-003f9382a027.png)
when I change position to relative highlighted element appears
![image](https://user-images.githubusercontent.com/10722240/112469692-659fb980-8d87-11eb-95ae-a8c5112f7148.png)

this is angular material code for fixed position sidenav:
https://stackblitz.com/angular/bqnrdboavxb?file=src%2Fapp%2Fsidenav-fixed-example.ts
