### ISSUE TITLE
Incorrect offset for popover.side: "right"

### ISSUE THREAD

**Issue by abvas** [kamranahmedse/driver.js#521]
If popover.side: "right" is set, then popover is offset to the left.

You can see this even on the "popover-position" demo

1. Load the page:
https://driverjs.com/docs/popover-position

2. Select "Right Start", "Right Center" or "Right End"
3. 
![right](https://github.com/user-attachments/assets/5c5e5245-6f2d-4104-a058-8a4e5c4eb106)

**Most likely, the scrollbar is taken into account here and "window.innerWidth" is used
I think that the situation will be corrected by using "document.documentElement.clientWidth" to exclude the scrollbar.**

**Comment by kamranahmedse** [comment]
Thank you for reporting, this should be fixed along with https://github.com/kamranahmedse/driver.js/issues/531

**Comment by abvas** [comment]
Thank you for looking into this issue.
But unfortunately the update did not fix the incorrect behavior.
I tried both version 1.3.4 and version 1.3.5

Here is a live example:
[https://codepen.io/abvas/pen/ZYzdQEM](https://codepen.io/abvas/pen/ZYzdQEM)

Please note that this behavior only appears if the scrollbar is visible on the page.

As far as I remember, in the previous version, I fixed this problem by replacing in two places
`**window.innerWidth** with **document.documentElement.clientWidth**`
