### ISSUE TITLE
[Feature request] New events

### ISSUE THREAD

**Issue by Rombecchi** [kamranahmedse/driver.js#69]
It will be very helpful if there was these events:
- **onBegins**: called before the tour starts
- **onDone**: called when user click on "done" buttons (tour is completed in all parts)
- **onClosed**: called when user click "close" or outside (the tour is not completed)

These actions will encourage to use cookies to show the joyride.

PS: please add some extra css classes to "done" button (ex: "driver-next-btn driver-done-btn")

**Comment by cherrygirl69** [comment]
CSS classes

**Comment by alexisab** [comment]
These features would really be appreciated, do you know if there is any progress on them?

**Comment by Naren-hybreeder** [comment]
@alexisab @Rombecchi 

Have you found the solution?

**Comment by Rombecchi** [comment]
Nope...

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. There are more simplified hooks which give you more control over the popover and the whole lifecycle. Please have a [look at the docs](https://driverjs.com/docs/configuration/) and do let me know if you face any issues.

**Comment by welljs** [comment]
2024 and version 1.3 released, but it's still not clear how to find out if the user pressed Done or not. Can anybody explain, please
